server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  application:
    name: hora-mundial

# Configuración de OpenAPI (Swagger UI)
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    enabled: true
  show-actuator: false
  cache:
    disabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Configuración de registro
logging:
  level:
    root: INFO
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuración del cliente HTTP
app:
  world-time-api:
    base-url: http://worldtimeapi.org/api/timezone
