name: Java CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with Maven
      run: mvn -B test
    - uses: mr-smithers-excellent/docker-build-push-action@v6
      with:
        image: mnustes/horamundial
        tag: ${{ github.sha }}
        registry: docker.io
        dockerfile: Dockerfile
        username: mnustes
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Trigger CD workflow
      uses: peter-evans/repository-dispatch@v2
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: manustes/horamundial-gitops
        event-type: app-update
        client-payload: '{"sha": "${{ github.sha }}"}'
        
      
        
      